[build]
  publish = "out"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# SPA fallback - redirect all non-file requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[dev]
  command = "npm run dev"
  port = 3000
  publish = "out"

